config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :clubs do
    resources :comments, only: [:create, :destroy, :index]
    resources :meetings, only: [:create]
  end
  resources :books, only: [:show]
  resources :memberships, only: [:create, :destroy]
  get '/profile', to: 'users#show', as: 'profile'
  get '/about', to: 'pages#about', as: 'about'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :comments
  has_many :meetings
  belongs_to :current_book, class_name: "Book"
  belongs_to :organizer, class_name: "User"

  validates :name,
    presence: true,
    length: { minimum: 3, maximum: 70 },
    uniqueness: true

  validates :description,
    length: { maximum: 140 }

  validates :organizer_id,
    presence: true

  def assign_book(title)
    self.current_book = Book.find_by(title: title) || AmazonApi.item_search(Book.new(title: title))
  end
  
  def has_current_book?
    current_book.present?
  end

  def self.search(query)
    where("plainto_tsquery(?) @@ " +
          "to_tsvector('english', name || ' ' || description)",
          query)
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :authenticate_user, except: :index
  before_action :authorize_organizer, only: [:edit, :update, :destroy]

  def index
    if params[:query]
      @query = params[:query]
      @clubs = Club.search(@query)
    else
      @clubs = Club.all
    end
  end

  def show
    @comment = Comment.new
    @club = Club.find(params[:id])
    @meetings = @club.meetings
    @meeting = Meeting.new
    if !@club.current_book.nil?
      @comments = @club.comments.where(book_id: @club.current_book.id)
    end
    if @club.users.include?(current_user)
      @membership = Membership.find_by(user_id: current_user.id, club_id: @club.id)
    end
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params.merge(organizer: current_user))
    if params[:club][:current_book].present?
      @club.assign_book(params[:club][:current_book])
    end
    if @club.save
      @club.users << current_user
      redirect_to @club, notice: "New Club Created!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if params[:club][:current_book].present?
      @club.assign_book(params[:club][:current_book])
    end
    if @club.update_attributes(club_params)
      redirect_to @club, notice: "Book Club Updated!"
    else
      render :edit
    end
  end

  def destroy
    @club.destroy
    redirect_to clubs_path, notice: "Club Deleted!"
  end

  private

  def club_params
    params.require(:club).permit(:name, :description)
  end

  def authorize_organizer
    @club = Club.find(params[:id])
    redirect_to @club if @club.organizer != current_user
  end
end

app/views/clubs/_form.html.erb
<div class="large-6 small-12 large-centered columns club-form">
  <%= form_for @club do |f| %>

  <div class="club-form-errors">
    <% if @club.errors.any? %>
    <h3>Book Club not created.</h3>
    <% @club.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
    <% end %>
    <% end %>
  </div>

  <%= f.label :name, "Book Club Name" %>
  <br>
  <%= f.text_field :name, size: 40 %>
  <br>
  <%= f.label :description %>
  <br>
  <%= f.text_field :description, size: 40 %>
  <br>
  <%= f.label :current_book, "Currently Reading (You can pick this later)" %>
  <br>
  <%= f.text_field :current_book,
      value: (@club.current_book.title unless @club.current_book.nil?),
      size: 40 %>
  <br>

  <%= f.submit "Save Club", id: "club-save-button" %>
  <% end %>

</div>

app/views/clubs/edit.html.erb
<div class="clubs-container">
  <div class="row">
    <div class="small-12 columns">
      <h1>Edit Settings for <%= @club.name %></h1>
      <%= render "form" %>
      <div>
        <p class="club-delete">
          <%= link_to fa_icon("times-circle lg", text: "Delete This Club"),
              club_path(@club),
              method: :delete, data: { confirm: "Are you sure?" },
              class: "delete-button" %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/clubs/index.html.erb
<div class="clubs-container">
  <div id="club-index-header">
    <h1>Find a Book Club</h1>
  </div>
  <div class="row">
    <div class="small-8 small-centered columns club-query-create">
      <% if @query %>
        <h1>Results for '<%= @query %>'</h1>
      <% end %>
      <div id="search">
        <%= form_tag clubs_path, method: :get do %>
          <%= text_field_tag :query, nil, placeholder: "Search Clubs" %>
          <%= submit_tag "Search", class: "create-button" %>
        <% end %>
      </div>
      <% if current_user %>
        <p id="create">
          <%= link_to "Create New Book Club", new_club_path, class: "create-button" %>
        </p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
        <% @clubs.each do |club| %>
          <li>
            <div class="club">
              <% if !club.current_book.nil? %>
                <%= image_tag club.current_book.medium_image %>
              <% end %>
              <div class="club-text"></div>
              <h3><%= link_to club.name, club %></h3>
              <p><%= club.description %></p>
              <% if club.current_book.nil? %>
                <p>[ Deciding on a New Book... ]</p>
              <% else %>
                <p>Reading: <span class="book-title"><%= club.current_book.title %></span></p>
              <% end %>
            <div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/clubs/new.html.erb
<div class="clubs-container">
  <div class="row">
    <div class="small-12 columns">
      <h1>Create New Book Club</h1>
      <%= render "form" %>

    </div>
  </div>
</div>

app/views/clubs/show.html.erb
<div class="clubs-container">
  <div class="row">
    <div class="small-12 columns club-page-header">
      <h1><%= @club.name %></h1>
      <div class="row">
        <div class="small-10 columns club-page-left">
          <h2><%= @club.description %></h2>
          <% unless @club.users.include? current_user %>
            <%= form_for Membership.new do |f| %>
              <%= f.hidden_field :club_id, value: @club.id %>
              <%= f.submit "Join this Book Club", id: "join-club" %>
            <% end %>
          <% end %>
          <h4>Organizer: <%= @club.organizer.name %></h4>
          <h4>Members:</h4>
          <% @club.users.each do |user| %>
            <span class="gravatar"><%= image_tag user.gravatar_url, alt: user.name %></span>
          <% end %>
        </div>
        <div class="small-2 columns club-page-right">
          <% if @club.current_book.nil? %>
            <h4>
              In between books right now. (Organizer can pick a book in club Settings.)
            </h4>
          <% else %>
            <h4>Reading: </h4>
            <% if @club.current_book.medium_image.nil? %>
              <p><%= fa_icon("book 5x") %></p>
            <% else %>
              <p><%= image_tag(@club.current_book.medium_image) %></p>
            <% end %>
            <p><%= @club.current_book.title %></p>
            <p>
              <% if !@club.current_book.amazon_url.nil? %>
                <%= link_to @club.current_book.amazon_url, target: "_blank" do %>
                  I need the book <%= fa_icon("external-link") %>
              <% end %>
              <% end %>
            </p>
          <% end %>
        </div>
      </div>

      <% if @club.users.include? current_user %>
      <h4 id="club-meetings">Meet</h4>
      <% if @club.organizer == current_user %>
        <div id="meetings-form">
          <%= form_for([@club, @meeting]) do |f| %>
            <% if @meeting.errors.any? %>
              <% @meeting.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
              <% end %>
            <% end %>
            <h4>Send a new event invite via Google Calendar to all group members:</h4>
            <%= f.text_field :meeting_time, size: 40, placeholder: "When?" %>
            <p id="meeting-time-info">(What can I write here?)</p>
            <div id="meeting-instructions">
              <h4>GatsBee can understand dates, for example:</h4>
              <p>This Tuesday at 5PM</p>
              <p>Friday 10:00</p>
              <p>Tomorrow at 7 in the evening</p>
              <p>January 5 at 7pm</p>
              <p>1 week hence</p>
              <p>1/22/2015 at noon</p>
            </div>
            <%= f.text_field :location, size: 40, placeholder: "Where?" %>
            <%= f.submit "Create Meeting", class: "new-meeting-button" %>
          <% end %>
        <% end %>
      </div>
      <% if !@meetings.nil? %>
        <h4 class="meeting">Upcoming Meetings:</h4>
        <% @meetings.each do |meeting| %>
          <% if meeting.formatted_time > Time.now %>
            <h4 class="meeting">
              <%= meeting.formatted_time.localtime.strftime("%A, %B %d, %Y, %l:%M %p") %> at <%= meeting.location %>
            </h4>
          <% end %>
        <% end %>
      <% end %>

      <h4 id="club-discussion">Discuss</h4>
        <%= form_for([@club, @comment]) do |f| %>
          <% if !@errors.nil? %>
            <% @errors.each do |msg| %>
            <div>
              <%= msg %>
            </div>
            <% end %>
          <% end %>
          <div class="row">
            <div class="small-5 small-centered columns">
              <%= f.select(:kind, options_for_select([["Comment", "remark"],
              ["Discussion Question", "question"]])) %>
            </div>
          </div>
          <%= f.text_area :content, size: "33x4", id: "comment-content" %>
          <br>
          <%= f.submit "Post", class: "new-comment-button" %>
        <% end %>
      <% end %>
      <% if !@comments.nil? %>
        <div id="club-comments">
          <h4>
            <% if !@club.current_book.nil? %>
              Currently showing discussion related to <%= @club.current_book.title %>.
            <% end %>
            <%= link_to "Discussion history for #{@club.name}", club_comments_path(@club) %>
          </h4>
          <%= render @comments %>
        </div>
      <% end %>
      <% if !@club.current_book.nil? %>
        <%= link_to book_path(@club.current_book) do %>
          <h4 id="club-discover">
            Discover questions and books related to <%= @club.current_book.title %>
          </h4>
        <% end %>
      <% end %>
      <% if @club.users.include?(current_user) &&
        @club.organizer != current_user %>
        <p class="delete-membership">
          <%= link_to fa_icon("frown-o", text: "Leave this Book Club"),
          @membership, method: :delete, data: { confirm: "Are you sure?" },
          class: "delete-button" %>
        </p>
      <% end %>
      <% if @club.organizer == current_user %>
        <h4 id="club-settings">
          <%= link_to fa_icon("wrench", text: "Settings"),
          edit_club_path(@club) %> (You're the organizer)
        </h4>
      <% end %>
    </div>
  </div>
</div>