config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :clubs do
    resources :comments, only: [:create, :destroy, :index]
    resources :meetings, only: [:create]
  end
  resources :books, only: [:show]
  resources :memberships, only: [:create, :destroy]
  get '/profile', to: 'users#show', as: 'profile'
  get '/about', to: 'pages#about', as: 'about'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic

  has_gravatar
  has_many :memberships
  has_many :clubs, through: :memberships
  has_many :organized_clubs, class_name: "Club", foreign_key: "organizer_id"
  has_many :comments
  has_many :meetings

  def refresh
    uri = URI.parse("https://www.googleapis.com/oauth2/v3/token")
    response = Net::HTTP.post_form(uri,
      { "client_id" => ENV['CLIENT_ID'],
        "client_secret" => ENV['CLIENT_SECRET'],
        "refresh_token" => self.refresh_token,
        "grant_type" => "refresh_token"
        }
      )
    self.update_attributes(
      oauth_token: JSON.parse(response.body)["access_token"],
      oauth_expires_at: DateTime.now.advance(seconds: JSON.parse(response.body)["expires_in"])
      )
  end

  def self.from_omniauth(auth)
    User.where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.refresh_token = auth.credentials.refresh_token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def comment_feed
    ActiveRecord::Base.connection.execute(
    "select comments.content, comments.kind, clubs.name
    from comments
    join clubs on clubs.id = comments.club_id
    where age(comments.created_at) < '7 days' and club_id in (
      select club_id
      from memberships
      where user_id = #{self.id})"
    ).to_a
  end

  def clubs_and_books
    ActiveRecord::Base.connection.execute(
    "select clubs.id, clubs.name, books.title as book_title, clubs.organizer_id
    from clubs
    join books on books.id = clubs.current_book_id
    join memberships on memberships.club_id = clubs.id
    where memberships.user_id = #{self.id}"
    ).to_a
  end


  def has_email?
    email.present?
  end

  def has_name?
    name.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user

  def show
    @user = current_user
    @comments = @user.comment_feed
    @clubs = @user.clubs_and_books
  end
end

app/views/users/show.html.erb
<div class="profile-container">
  <div class="row">
    <div class="small-12 columns">
      <span class="gravatar"><%= image_tag @user.gravatar_url(size: 110) %></span>
      <h1><%= @user.name %></h1>
    </div>
  </div>
  <div class="row">
    <div class="large-6 small-12 columns">
      <% if @clubs.empty? %>
        <%= link_to clubs_path do %>
          <div class="profile-club">
            <h3>Go Join Some Clubs!</h3>
          </div>
        <% end %>
      <% else %>
        <% @clubs.each do |club| %>
          <%= link_to club_path(club["id"]) do %>
            <div class="profile-club">
              <h3>
                <% if club["organizer_id"].to_i == current_user.id %>
                  <%= fa_icon("user", text: club["name"]) %>
                <% else %>
                  <%= fa_icon("bookmark", text: club["name"]) %>
                <% end %>
              </h3>
              <% if !club["book_title"].nil? %>
                <h4><%= club["book_title"] %></h4>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="large-6 small-12 columns comment-feed">
      <h2>Comment Feed</h2>
      <% if @comments.empty? %>
        <h3>Nothing here yet!</h3>
      <% else %>
        <% @comments.each do |comment| %>
          <p>
            <%= fa_icon("quote-left", class: "profile-#{comment["kind"]}") %>
            <%= comment["content"][0..100] %> ...
            <%= fa_icon("quote-right", class: "profile-#{comment["kind"]}") %>
            in <%= comment["name"] %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>