config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :clubs do
    resources :comments, only: [:create, :destroy, :index]
    resources :meetings, only: [:create]
  end
  resources :books, only: [:show]
  resources :memberships, only: [:create, :destroy]
  get '/profile', to: 'users#show', as: 'profile'
  get '/about', to: 'pages#about', as: 'about'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="row">
    <div class="small-12 columns">
      <ul class="small-block-grid-3">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", "#{about_path}#contact" %></li>
        <li><%= link_to "Contribute", "#{about_path}#contribute" %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="row">
    <div class="small-3 columns">
      <h1><%= link_to "GatsBee", root_path %></h1>
    </div>

    <% if current_user %>
      <div class="small-4 columns">
        <ul class="small-block-grid-3">
          <li class="option"><p><%= link_to "Clubs", clubs_path %></p></li>
          <li class="option"><p><%= link_to "Profile", profile_path %></p></li>
          <li class="option"><p><%= link_to "Sign Out", signout_path %></p></li>
        </ul>
      </div>
    <% else %>
      <div class="large-1 small-3 columns">
        <ul class="small-block-grid-1">
          <li class="option">
            <p>
              <%= link_to "Sign in", "/auth/google_oauth2" %>
            </p>
          </li>
        </ul>
      </div>
    <% end %>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GatsBee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

  <% if flash.any? %>
    <div class="flash"><%= flash.notice %></div>
  <% end %>

  <div class="body-container">
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>
</body>
</html>